function attitude = leg_attitude(phi_1_,phi_2_)
%LEG_ATTITUDE
%    ATTITUDE = LEG_ATTITUDE(PHI_1_,PHI_2_)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-03 01:51:40

t2 = cos(phi_2_);
t3 = sin(phi_2_);
t4 = pi./2.0;
t5 = phi_1_./2.0;
t6 = phi_2_./2.0;
t7 = -t4;
t8 = t2.*(2.1e+1./1.0e+2);
t9 = t5+t6+t7;
t10 = cos(t9);
t11 = t10.*(2.1e+1./2.5e+1);
t12 = acos(t11);
t13 = t12.*2.0;
t14 = -t13;
t15 = phi_2_+t14;
t16 = cos(t15);
t17 = sin(t15);
t18 = t16./4.0;
attitude = [sqrt((t8-t18).^2+(t3.*(2.1e+1./1.0e+2)-t17./4.0).^2),t4-atan2(t3.*(2.1e+1./1.0e+2)-t17./4.0,t8-t18)];
end
