function torque = torque_transform(F,T_p,phi_1_,phi_2_)
%TORQUE_TRANSFORM
%    TORQUE = TORQUE_TRANSFORM(F,T_p,PHI_1_,PHI_2_)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-03 01:51:40

t2 = cos(phi_2_);
t3 = sin(phi_2_);
t5 = phi_1_+phi_2_;
t10 = sqrt(2.0);
t11 = phi_1_./2.0;
t12 = phi_2_./2.0;
t4 = imag(t2);
t6 = real(t2);
t7 = imag(t3);
t8 = real(t3);
t9 = cos(t5);
t13 = t2.*(2.1e+1./1.0e+2);
t14 = t3.*(2.1e+1./1.0e+2);
t21 = t3.*2.1e-1i;
t25 = t11+t12;
t15 = -t13;
t17 = t4.*(2.1e+1./1.0e+2);
t18 = t6.*(2.1e+1./1.0e+2);
t19 = t7.*(2.1e+1./1.0e+2);
t20 = t8.*(2.1e+1./1.0e+2);
t26 = -t21;
t27 = cos(t25);
t28 = sin(t25);
t29 = t9.*8.93025e-3;
t30 = t28.*(2.1e+1./2.5e+1);
t49 = t29+1.638225e-2;
t31 = acos(t30);
t50 = 1.0./sqrt(t49);
t32 = t31.*2.0;
t55 = t10.*t27.*t50.*9.45e-2;
t33 = -t32;
t56 = t55+1.0;
t34 = phi_2_+t33;
t35 = cos(t34);
t36 = sin(t34);
t37 = imag(t35);
t38 = real(t35);
t39 = imag(t36);
t40 = real(t36);
t41 = t35./4.0;
t42 = t36./4.0;
t47 = t36.*2.5e-1i;
t66 = t35.*t56.*(-1.0./4.0);
t67 = t36.*t56.*(-1.0./4.0);
t43 = t37./4.0;
t44 = t38./4.0;
t45 = t39./4.0;
t46 = t40./4.0;
t51 = t15+t41;
t53 = (t13-t41).^2;
t54 = (t14-t42).^2;
t68 = t14+t67;
t69 = t13+t66;
t57 = t26+t47+t51;
t61 = t53+t54;
t60 = abs(t57);
t63 = 1.0./sqrt(t61);
t62 = 1.0./t60;
torque = [-F.*(t10.*t27.*t35.*t50.*t62.*(t17+t20-t43-t46).*2.3625e-2-t10.*t27.*t36.*t50.*t62.*(t18-t19-t44+t45).*2.3625e-2)-T_p.*t63.*(t10.*t27.*t35.*t50.*t62.*(t18-t19-t44+t45).*2.3625e-2+t10.*t27.*t36.*t50.*t62.*(t17+t20-t43-t46).*2.3625e-2);-F.*(t62.*t68.*(t18-t19-t44+t45)-t62.*t69.*(t17+t20-t43-t46))+T_p.*t63.*(t62.*t68.*(t17+t20-t43-t46)+t62.*t69.*(t18-t19-t44+t45))];
end
