function pos = leg_pos(phi1,phi4)
%LEG_POS
%    POS = LEG_POS(PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-04 00:10:51

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = t2.*(2.1e+1./1.0e+2);
t7 = t3.*(2.1e+1./1.0e+2);
t8 = t2.*(2.1e+1./2.0e+2);
t9 = t3.*(2.1e+1./2.0e+2);
t10 = t4.*(2.1e+1./1.0e+2);
t11 = t5.*(2.1e+1./1.0e+2);
t12 = t4.*(2.1e+1./2.0e+2);
t13 = t5.*(2.1e+1./2.0e+2);
t14 = -t7;
t15 = -t8;
t16 = -t11;
t17 = -t12;
t18 = t6+t14;
t19 = t10+t16;
t20 = t18.^2;
t21 = t19.^2;
t22 = t20./4.0;
t23 = t21./4.0;
t24 = t20+t21;
t25 = t24.^2;
t27 = t9+t15+t24;
t26 = -t25;
t28 = 1.0./t27;
t29 = t22+t23+t26;
t30 = sqrt(t29);
t31 = t13+t17+t30;
t32 = t28.*t31;
t33 = atan(t32);
t34 = t33.*2.0;
t35 = cos(t34);
t36 = sin(t34);
t37 = t35./4.0;
pos = [sqrt((t10+t36./4.0).^2+(t6+t37).^2);pi./2.0-atan2(t4.*(2.1e+1./1.0e+2)+t36./4.0,t6+t37)];
end
