function T_r = leg_conv_reverse(T1,T2,phi1,phi4)
%LEG_CONV_REVERSE
%    T_r = LEG_CONV_REVERSE(T1,T2,PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-04 00:10:52

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = t2.*(2.1e+1./1.0e+2);
t7 = t3.*(2.1e+1./1.0e+2);
t8 = t2.*(2.1e+1./2.0e+2);
t9 = t3.*(2.1e+1./2.0e+2);
t10 = t4.*(2.1e+1./1.0e+2);
t11 = t5.*(2.1e+1./1.0e+2);
t12 = t4.*(2.1e+1./2.0e+2);
t13 = t5.*(2.1e+1./2.0e+2);
t18 = t4.*2.1e-1i;
t14 = -t7;
t15 = -t8;
t16 = -t11;
t17 = -t12;
t19 = t6+t14;
t20 = t10+t16;
t21 = t19.^2;
t22 = t20.^2;
t23 = t21./4.0;
t24 = t22./4.0;
t25 = t21+t22;
t26 = t25.^2;
t28 = t9+t15+t25;
t27 = -t26;
t29 = 1.0./t28;
t30 = t23+t24+t27;
t31 = sqrt(t30);
t32 = t13+t17+t31;
t33 = t29.*t32;
t34 = atan(t33);
t35 = t34.*2.0;
t36 = -t35;
t37 = cos(t35);
t38 = sin(t35);
t39 = phi1+t36;
t41 = t37./4.0;
t42 = t38./4.0;
t44 = t38.*2.5e-1i;
t40 = sin(t39);
t45 = t19+t41;
t46 = t20+t42;
t48 = t6+t18+t41+t44;
t43 = 1.0./t40;
t47 = 1.0./t45;
t49 = angle(t48);
t50 = -t49;
t51 = t46.*t47;
t52 = atan(t51);
t57 = t35+t50;
t53 = -t52;
t58 = t50+t52;
t54 = phi4+t53;
t55 = sin(t54);
t56 = 1.0./t55;
T_r = [t43.*t56.*(T2.*t40.*cos(t58).*(2.1e+1./1.0e+2)+T1.*t55.*cos(t57).*(2.1e+1./1.0e+2)).*(-2.267573696145125e+1);t43.*t56.*(T2.*t40.*sin(t58).*(2.1e+1./1.0e+2)+T1.*t55.*sin(t57).*(2.1e+1./1.0e+2)).*sqrt((t6+t41).^2+(t10+t42).^2).*(-2.267573696145125e+1)];
end
