function leg_posture = leg_posture(phi1,phi4)
%LEG_POSTURE
%    LEG_POSTURE = LEG_POSTURE(PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-13 22:44:20

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = t2.*(2.1e+1./1.0e+2);
t7 = t3.*(2.1e+1./1.0e+2);
t8 = t2.*(2.1e+1./2.0e+2);
t9 = t3.*(2.1e+1./2.0e+2);
t10 = t4.*(2.1e+1./1.0e+2);
t11 = t5.*(2.1e+1./1.0e+2);
t15 = t4.*1.05e-1i;
t16 = t5.*1.05e-1i;
t12 = -t7;
t13 = -t8;
t14 = -t11;
t17 = -t15;
t18 = t6+t12;
t19 = t10+t14;
t20 = t18.^2;
t21 = t19.^2;
t22 = t20./4.0;
t23 = t21./4.0;
t24 = t20+t21;
t25 = t24.^2;
t26 = -t25;
t27 = t22+t23+t26;
t28 = sqrt(t27);
t29 = t28.*1i;
t30 = t9+t13+t16+t17+t24+t29;
t31 = angle(t30);
t32 = t31.*2.0;
t33 = cos(t32);
t34 = sin(t32);
t35 = t33./4.0;
leg_posture = [sqrt((t10+t34./4.0).^2+(t6+t35).^2);pi./2.0-atan2(t4.*(2.1e+1./1.0e+2)+t34./4.0,t6+t35)];
end
