function leg_posture = leg_posture(l1,l2,l3,l4,l5,phi1,phi4)
%LEG_POSTURE
%    LEG_POSTURE = LEG_POSTURE(L1,L2,L3,L4,L5,PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-04 02:06:39

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = l2.^2;
t7 = l3.^2;
t12 = l5./2.0;
t8 = l1.*t2;
t9 = l4.*t3;
t10 = l1.*t4;
t11 = l4.*t5;
t13 = -t7;
t16 = -t12;
t14 = -t8;
t15 = -t11;
t17 = t10+t15;
t18 = l5+t9+t14;
t19 = t17.^2;
t20 = t18.^2;
t21 = l2.*t18.*2.0;
t22 = l2.*t17.*2.0i;
t23 = -t22;
t24 = t6.*t19.*4.0;
t25 = t6.*t20.*4.0;
t26 = t6+t13+t19+t20;
t27 = t26.^2;
t28 = -t27;
t29 = t24+t25+t28;
t30 = sqrt(t29);
t31 = t30.*1i;
t32 = t21+t23+t26+t31;
t33 = angle(t32);
t34 = t33.*2.0;
t35 = sin(t34);
t36 = cos(t34);
t37 = l2.*t36;
leg_posture = [sqrt((t8+t16+t37).^2+(t10+l2.*t35).^2);pi./2.0-atan2(t10+l2.*t35,t8+t16+t37)];
end
